### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by JosephRedfern** [duncan-clark/duncan-clark.github.io#1]
Hello Duncan!

I enjoyed your article on Strava network analysis, and noticed that there were some broken links, caused by some unnecessary square brackets in your markdown -- for instance here: https://github.com/duncan-clark/duncan-clark.github.io/blob/master/_pages/UCLA_net_strava.Rmd#L41.

I would submit a PR but didn't want to set up a build environment to re-run your experiments, so though an issue might do!

**Comment by duncan-clark** [comment]
Thanks! All fixed, the Rmd files have to be built locally into HTML, when updating, which isn't a very good solution but its the best I could do at the moment. I think there is a better way of doing it but seems more complex.
